require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
// require("jquery")
require("javascripts/jquery-1.11.1.min.js")
require("javascripts/bootstrap")
// require("javascripts/megamenu.js")
require("javascripts/responsiveslides.min.js")
// require("javascripts/jquery.flexslider.js")
// require("javascripts/jquery.jscrollpane.min.js")
require("packs/custom.js")
require("javascripts/jquery.flexisel.js")
// require("javascripts/simpleCart.min.js")

